(function(){
  var API='https://nmeoakrpafxhpdrplsuo.supabase.co/functions/v1/vmeste-circle-api';
  var loading=false,people=[];
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function session(){try{return JSON.parse(localStorage.getItem('vmeste_session_v1')||'null')}catch(e){return null}}
  function token(){var s=session();return s&&s.access_token||''}
  function api(action,payload){var t=token();if(!t)return Promise.reject(new Error('LOGIN'));return fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+t},body:JSON.stringify(Object.assign({action:action},payload||{}))}).then(function(r){return r.json().catch(function(){return{error:'Некорректный ответ сервера'}}).then(function(d){if(!r.ok)throw new Error(d.error||'Ошибка запроса');return d})})}
  function avatar(p){var name=p.display_name||'У';if(p.avatar_url)return '<span class="aroundPersonAvatar aroundPersonAvatarPhoto" style="background-image:url(\''+esc(p.avatar_url)+'\')"></span>';return '<span class="aroundPersonAvatar">'+esc(name.trim().slice(0,1).toUpperCase()||'У')+'</span>'}
  function context(p){var d=Number(p.distance)||2;if(p.via_name)return 'через '+esc(p.via_name)+' · '+d+' рукопожатия';return d+' рукопожатия от вас'}
  function card(p){return '<article class="aroundPersonCard">'+avatar(p)+'<div class="aroundPersonCopy"><h3>'+esc(p.display_name||'Участник')+'</h3><p>'+context(p)+'</p></div><button type="button" class="aroundPersonAdd" data-around-add="'+esc(p.id)+'">Добавить в круг</button></article>'}
  function mount(){var home=document.querySelector('[data-view="home"]');if(!home)return null;var root=document.getElementById('around-people-root');if(root)return root;root=document.createElement('section');root.id='around-people-root';root.className='aroundPeopleRoot';var discovery=document.getElementById('home-discovery-root'),feed=document.getElementById('afisha-root');home.insertBefore(root,discovery||feed||null);root.addEventListener('click',function(e){var b=e.target.closest('[data-around-add]');if(!b)return;if(!token()){if(typeof openView==='function')openView('login');return}b.disabled=true;b.textContent='Отправляю…';api('send_request',{target_user_id:b.dataset.aroundAdd}).then(function(){b.textContent='Запрос отправлен';b.classList.add('is-sent');document.dispatchEvent(new CustomEvent('vmeste-circle-changed'));setTimeout(load,300)}).catch(function(){b.disabled=false;b.textContent='Повторить'})});return root}
  function render(){var root=mount();if(!root)return;if(!token()){root.innerHTML='';root.hidden=true;return}root.hidden=false;if(loading){root.innerHTML='<div class="aroundPeopleHead"><div><span class="ey">ЛЮДИ ВОКРУГ</span><h2>Через знакомых</h2></div></div><div class="aroundPeopleLoading">Ищу связи…</div>';return}if(people.length){root.innerHTML='<div class="aroundPeopleHead"><div><span class="ey">ЛЮДИ ВОКРУГ</span><h2>Через знакомых</h2></div><small>2–3 рукопожатия</small></div><div class="aroundPeopleShelf">'+people.map(card).join('')+'</div>';return}root.innerHTML='<div class="aroundPeopleHead"><div><span class="ey">ЛЮДИ ВОКРУГ</span><h2>Через знакомых</h2></div><small>2–3 рукопожатия</small></div><div class="aroundPeopleEmpty">Здесь появятся люди через 2–3 рукопожатия, когда ваш круг начнёт расти.</div>'}
  function load(){if(!token()){people=[];loading=false;render();return Promise.resolve()}loading=true;render();return api('around_people').then(function(d){people=d.people||[]}).catch(function(){people=[]}).finally(function(){loading=false;render()})}
  function boot(){mount();load();var nav=document.querySelector('.nav[data-go="home"]');if(nav)nav.addEventListener('click',function(){setTimeout(load,80)});document.addEventListener('vmeste-circle-changed',function(){setTimeout(load,80)});document.addEventListener('visibilitychange',function(){if(!document.hidden)load()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();