(function(){
  var GROUPS_KEY='vmeste_groups_proto_v1';
  var LINKS_KEY='vmeste_event_group_proto_v1';
  var MEMBER_KEY='vmeste_community_member_state_v1';
  var CHAT_KEY='vmeste_community_chat_proto_v1';
  var activeGroupId=null,activeTab='events',lastEvents=null,lastChronicle=null;

  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function read(key,fallback){try{var raw=localStorage.getItem(key);if(!raw)return fallback;var v=JSON.parse(raw);return v==null?fallback:v}catch(e){return fallback}}
  function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch(e){}}
  function groups(){var a=read(GROUPS_KEY,[]);return Array.isArray(a)?a:[]}
  function links(){var m=read(LINKS_KEY,{});return m&&typeof m==='object'?m:{}}
  function group(){return groups().find(function(g){return String(g.id)===String(activeGroupId)})||null}
  function patchGroup(id,patch){var a=groups(),g=a.find(function(x){return String(x.id)===String(id)});if(!g)return null;Object.assign(g,patch);write(GROUPS_KEY,a);return g}
  function groupEventIds(){var m=links();return Object.keys(m).filter(function(id){return String(m[id])===String(activeGroupId)})}
  function session(){try{return JSON.parse(localStorage.getItem('vmeste_session_v1')||'null')}catch(e){return null}}
  function currentAccount(){try{return typeof account!=='undefined'?account:null}catch(e){return null}}
  function signedIn(){var s=session();return !!(s&&s.access_token)}
  function currentUserId(){var a=currentAccount(),s=session();return a&&a.user&&a.user.id||s&&s.user&&s.user.id||''}
  function accountName(){var a=currentAccount();return a&&a.profile&&a.profile.display_name||a&&a.user&&a.user.email||'Вы'}
  function eventParts(v){try{var p=new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'}).formatToParts(new Date(v)),g=function(t){var x=p.find(function(a){return a.type===t});return x?x.value:''};return{day:g('day'),month:g('month').replace('.','').toUpperCase(),time:g('hour')+':'+g('minute')}}catch(e){return{day:'',month:'',time:''}}}
  function memberWord(n){var m=Math.abs(n)%100,d=m%10;if(m>10&&m<20)return'участников';if(d===1)return'участник';if(d>1&&d<5)return'участника';return'участников'}
  function isOwner(g){if(g.is_owner===true||g.role==='owner'||g.role==='creator')return true;if(g.is_owner===false||g.role==='guest'||g.role==='member'||g.role==='admin')return false;return true}
  function memberMap(){var m=read(MEMBER_KEY,{});return m&&typeof m==='object'?m:{}}
  function setMemberState(g,state){var m=memberMap();m[g.id]=state;write(MEMBER_KEY,m)}
  function membership(g){if(isOwner(g))return'member';var m=memberMap();if(m[g.id])return m[g.id];if(g.membership_status==='accepted'||g.membership_status==='member')return'member';if(g.membership_status==='invited'||g.invited===true)return'invited';return'guest'}
  function canCreate(g){var state=membership(g);if(state!=='member')return false;return isOwner(g)||g.event_permission!=='owner'}
  function canSeePrivate(g){return g.access==='open'||membership(g)==='member'||isOwner(g)}

  function ensure(){if(document.querySelector('[data-view="community-detail"]'))return;var section=document.createElement('section');section.className='view communityDetailView';section.dataset.view='community-detail';section.innerHTML='<div id="community-detail-root"></div>';var app=document.querySelector('.app'),nav=document.getElementById('bottom-nav');if(app)app.insertBefore(section,nav||null)}
  function close(){activeGroupId=null;activeTab='events';lastEvents=null;lastChronicle=null;if(typeof window.openSocialCommunities==='function')window.openSocialCommunities();else if(typeof openView==='function')openView('communities')}

  function membershipActions(g){var state=membership(g);if(isOwner(g)||state==='member'||state==='declined')return'';if(g.access==='open')return '<div class="communityMembershipActions one"><button type="button" class="communityJoin" data-community-join>Вступить</button></div>';if(state==='invited')return '<div class="communityMembershipActions"><button type="button" class="communityJoin" data-community-join>Вступить</button><button type="button" class="communityDecline" data-community-decline>Отклонить</button></div>';return''}
  function hero(g){var cover=g.cover_url?'style="background-image:url(\''+esc(g.cover_url)+'\')"':'';var create=canCreate(g)?'<button type="button" class="communityHeroCreate" data-community-create-event aria-label="Создать событие">＋</button>':'';return '<div class="communityDetailHero '+(g.cover_url?'has-cover':'')+'" '+cover+'><button type="button" class="communityDetailBack" aria-label="Назад">‹</button><button type="button" class="communityDetailMenu" aria-label="Управление">•••</button><div class="communityDetailHeroShade"></div>'+create+'<div class="communityDetailHeroCopy"><span class="ey">СООБЩЕСТВО</span><h1>'+esc(g.name)+'</h1><p>'+esc(g.description||'Локальная группа')+'</p><small>'+Number(g.member_count||1)+' '+memberWord(Number(g.member_count||1))+'</small></div></div>'}
  function tabs(){return '<div class="communityDetailTabs"><button type="button" data-community-tab="events" class="'+(activeTab==='events'?'active':'')+'">События</button><button type="button" data-community-tab="members" class="'+(activeTab==='members'?'active':'')+'">Участники</button><button type="button" data-community-tab="album" class="'+(activeTab==='album'?'active':'')+'">Альбом</button></div>'}
  function eventCard(ev,history){var d=eventParts(ev.starts_at);return '<button type="button" class="communityEventCard" data-community-event="'+esc(ev.id)+'"><span class="communityEventDate"><b>'+esc(d.day)+'</b><small>'+esc(d.month)+'</small></span><span class="communityEventCopy"><strong>'+esc(ev.title)+'</strong><small>'+esc(d.time+(ev.location_name?' · '+ev.location_name:''))+'</small></span><span class="communityEventState">'+(history?'Было':'Открыть')+' ›</span></button>'}

  function eventsPanel(g){if(!canSeePrivate(g))return '<div class="communityDetailEmpty"><h3>Закрытое сообщество</h3><p>События станут доступны после вступления.</p></div>';var ids=groupEventIds();if(!signedIn())return '<div class="communityDetailEmpty"><h3>Войдите, чтобы увидеть события</h3><p>После входа здесь появятся события сообщества.</p></div>';if(lastEvents===null)return '<div class="communityDetailEmpty">Загружаю события…</div>';var all=[];(lastEvents.events||[]).forEach(function(e){all.push(e)});(lastEvents.invited_events||[]).forEach(function(e){if(e.invitation_status==='accepted')all.push(e)});var now=Date.now(),items=all.filter(function(e){return ids.indexOf(String(e.id))>=0&&!['finished','cancelled'].includes(e.status)&&new Date(e.starts_at).getTime()>=now}).sort(function(a,b){return new Date(a.starts_at)-new Date(b.starts_at)});if(!items.length)return '<div class="communityDetailEmpty"><h3>Пока нет ближайших событий</h3><p>'+(canCreate(g)?'Создайте первое событие для сообщества.':'Новые события появятся здесь.')+'</p></div>';var first=items[0],rest=items.slice(1);return '<div class="communityNext"><span class="eventInfoLabel">БЛИЖАЙШЕЕ</span>'+eventCard(first,false)+'</div>'+(rest.length?'<div class="communityAllEvents"><span class="eventInfoLabel">ВСЕ ПРЕДСТОЯЩИЕ</span>'+rest.map(function(e){return eventCard(e,false)}).join('')+'</div>':'')}

  function memberRows(g){var arr=Array.isArray(g.members)?g.members.slice():[];if(!arr.length)arr=[{id:currentUserId()||'me',display_name:accountName(),role:isOwner(g)?'owner':'member',mine:true}];return arr.map(function(p){var n=p.display_name||p.name||'Участник',letter=String(n).trim().slice(0,1).toUpperCase()||'У';var role=p.role==='owner'?'Создатель':p.role==='admin'?'Администратор':'Участник';var menu=isOwner(g)&&p.role!=='owner'&&!p.mine?'<button type="button" class="communityMemberMenu" data-community-member-menu="'+esc(p.id)+'" aria-label="Управление участником">•••</button>':'';return '<div class="communityMemberRow"><span class="communityMemberAvatar">'+esc(letter)+'</span><span class="communityMemberCopy"><strong>'+esc(n)+'</strong><small>'+role+'</small></span>'+menu+'</div>'}).join('')}
  function membersPanel(g){if(!canSeePrivate(g))return '<div class="communityDetailEmpty"><h3>Участники скрыты</h3><p>Список доступен участникам закрытого сообщества.</p></div>';var n=Number(g.member_count||1),invite=membership(g)==='member'||isOwner(g)?'<button type="button" class="communityInviteMembers">＋ Пригласить</button>':'';return '<div class="communityMembersHead"><strong>'+n+' '+memberWord(n)+'</strong>'+invite+'</div><div class="communityMemberList">'+memberRows(g)+'</div>'}

  function albumPanel(g){if(!canSeePrivate(g))return '<div class="communityDetailEmpty"><h3>Альбом скрыт</h3><p>Фото и видео доступны участникам сообщества.</p></div>';var ids=groupEventIds();if(lastChronicle===null)return '<div class="communityDetailEmpty">Загружаю альбом…</div>';var items=(lastChronicle&&lastChronicle.events||[]).filter(function(e){return ids.indexOf(String(e.id))>=0&&(e.cover_url||Number(e.media_count||0)>0)}).sort(function(a,b){return new Date(b.starts_at)-new Date(a.starts_at)});if(!items.length)return '<div class="communityDetailEmpty"><h3>Альбом пока пуст</h3><p>Фото и видео из событий этого сообщества появятся здесь автоматически.</p></div>';return '<div class="communityAlbumGrid">'+items.map(function(e){var bg=e.cover_url?'style="background-image:url(\''+esc(e.cover_url)+'\')"':'';return '<button type="button" class="communityAlbumTile '+(e.cover_url?'has-photo':'')+'" '+bg+' data-community-event="'+esc(e.id)+'"><span><strong>'+esc(e.title||'Событие')+'</strong><small>'+Number(e.media_count||0)+' медиа</small></span></button>'}).join('')+'</div>'}
  function content(g){if(activeTab==='members')return membersPanel(g);if(activeTab==='album')return albumPanel(g);return eventsPanel(g)}

  function chatMessages(g){var all=read(CHAT_KEY,{}),a=all[g.id];return Array.isArray(a)?a:[]}
  function saveChat(g,a){var all=read(CHAT_KEY,{});all[g.id]=a;write(CHAT_KEY,all)}
  function chatDock(g){if(g.chat_enabled!==true||membership(g)!=='member')return'';var a=chatMessages(g),last=a.slice(-2);return '<button type="button" class="communityChatDock" data-community-chat-open><span class="communityChatHandle"></span><span class="communityChatTitle">Чат сообщества</span><span class="communityChatPreview">'+(last.length?last.map(function(m){return '<b>'+esc(m.name||'Участник')+':</b> '+esc(m.text)}).join('<br>'):'Пока тихо. Напишите первым.')+'</span><span class="communityChatHint">Потяните вверх или нажмите, чтобы открыть</span></button>'}
  function openChat(g){document.querySelector('.communityChatOverlay')?.remove();var o=document.createElement('div');o.className='communityChatOverlay';o.innerHTML='<div class="communityChatFull"><div class="communityChatFullHead"><span class="communityChatGrab"></span><strong>'+esc(g.name)+'</strong></div><div class="communityChatMessages"></div><form class="communityChatComposer"><textarea maxlength="1200" rows="1" placeholder="Сообщение"></textarea><button type="submit">↑</button></form></div>';document.body.appendChild(o);var box=o.querySelector('.communityChatMessages'),form=o.querySelector('form'),ta=form.querySelector('textarea');function draw(){var a=chatMessages(g);box.innerHTML=a.length?a.map(function(m){return '<div class="communityChatBubble '+(m.mine?'mine':'')+'"><small>'+esc(m.name||'Участник')+'</small><span>'+esc(m.text)+'</span></div>'}).join(''):'<div class="communityChatEmpty">Начните разговор</div>';box.scrollTop=box.scrollHeight}function dismiss(){o.classList.add('closing');setTimeout(function(){o.remove();render()},170)}var sy=0;o.addEventListener('touchstart',function(e){sy=e.touches[0].clientY},{passive:true});o.addEventListener('touchend',function(e){if(e.changedTouches[0].clientY-sy>70)dismiss()},{passive:true});o.querySelector('.communityChatFullHead').onclick=dismiss;form.onsubmit=function(e){e.preventDefault();var t=ta.value.trim();if(!t)return;var a=chatMessages(g);a.push({id:Date.now(),name:accountName(),text:t,mine:true,created_at:new Date().toISOString()});saveChat(g,a);ta.value='';draw()};draw();setTimeout(function(){o.classList.add('open')},10)}

  function render(){ensure();var g=group(),root=document.getElementById('community-detail-root');if(!root)return;if(!g){root.innerHTML='<div class="communityDetailMissing"><button class="communityDetailBack">‹</button><h2>Сообщество не найдено</h2></div>';root.querySelector('.communityDetailBack').onclick=close;return}root.innerHTML=hero(g)+'<div class="communityDetailBody">'+membershipActions(g)+tabs()+'<div class="communityDetailContent">'+content(g)+'</div>'+chatDock(g)+'</div>';root.querySelector('.communityDetailBack').onclick=close;root.querySelector('.communityDetailMenu').onclick=function(){openManagement(g)};root.querySelectorAll('[data-community-tab]').forEach(function(b){b.onclick=function(){activeTab=b.dataset.communityTab;render();if(activeTab==='album')loadAlbum();if(activeTab==='events')loadEvents()}});root.querySelectorAll('[data-community-create-event]').forEach(function(b){b.onclick=function(){openCreateEvent(g)}});root.querySelectorAll('[data-community-event]').forEach(function(b){b.onclick=function(){if(typeof openEventView==='function')openEventView(b.dataset.communityEvent,'communities')}});var invite=root.querySelector('.communityInviteMembers');if(invite)invite.onclick=function(){openInvite(g)};var join=root.querySelector('[data-community-join]');if(join)join.onclick=function(){setMemberState(g,'member');patchGroup(g.id,{member_count:Number(g.member_count||0)+1});render();loadEvents()};var decline=root.querySelector('[data-community-decline]');if(decline)decline.onclick=function(){setMemberState(g,'declined');render()};root.querySelectorAll('[data-community-member-menu]').forEach(function(b){b.onclick=function(){openMemberMenu(g,b.dataset.communityMemberMenu)}});var chat=root.querySelector('[data-community-chat-open]');if(chat){chat.onclick=function(){openChat(g)};var sy=0;chat.addEventListener('touchstart',function(e){sy=e.touches[0].clientY},{passive:true});chat.addEventListener('touchend',function(e){if(sy-e.changedTouches[0].clientY>45)openChat(g)},{passive:true})}}

  async function loadEvents(){if(!signedIn()||typeof api!=='function')return;try{lastEvents=await api('list_events');if(activeTab==='events')render()}catch(e){lastEvents={events:[],invited_events:[]};if(activeTab==='events')render()}}
  async function loadAlbum(){if(!signedIn()){lastChronicle={events:[]};render();return}try{if(typeof eventRaw==='function')lastChronicle=await eventRaw('list_chronicle',{});else lastChronicle={events:[]};if(activeTab==='album')render()}catch(e){lastChronicle={events:[]};if(activeTab==='album')render()}}

  function openCreateEvent(g){sessionStorage.setItem('vmeste_group_event_context_v1',g.id);if(typeof openView==='function')openView('create');setTimeout(function(){var action=document.querySelector('[data-view="create"] [data-create-action="event"]');if(action)action.click();var form=document.getElementById('event-form');var old=document.querySelector('.communityCreateContext');if(old)old.remove();var box=document.createElement('div');box.className='communityCreateContext';box.innerHTML='<span>СОБЫТИЕ ДЛЯ СООБЩЕСТВА</span><strong>'+esc(g.name)+'</strong><small>Сообщество уже выбрано. После создания событие будет связано с ним автоматически.</small>';if(form)form.insertAdjacentElement('beforebegin',box)},40)}
  function openInvite(g){var url=location.origin+location.pathname+'#community-'+encodeURIComponent(g.id);var data={title:'ЛЯ',text:'Присоединяйся к сообществу «'+g.name+'» в ЛЯ.',url:url};if(navigator.share){navigator.share(data).catch(function(e){if(e&&e.name!=='AbortError')copyInvite(url)})}else copyInvite(url)}
  function copyInvite(url){if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(url).then(function(){alert('Ссылка-приглашение скопирована')}).catch(function(){prompt('Скопируйте ссылку',url)});else prompt('Скопируйте ссылку',url)}
  function openMemberMenu(g,id){document.querySelector('.communityActionOverlay')?.remove();var o=document.createElement('div');o.className='communityActionOverlay';o.innerHTML='<div class="communityActionSheet"><div class="communityActionHead"><h2>Участник</h2><button type="button">×</button></div><button type="button" class="communityManageDanger" data-remove-member>Удалить из сообщества</button></div>';document.body.appendChild(o);o.querySelector('.communityActionHead button').onclick=function(){o.remove()};o.querySelector('[data-remove-member]').onclick=function(){if(!confirm('Удалить участника из сообщества?'))return;var members=Array.isArray(g.members)?g.members.filter(function(x){return String(x.id)!==String(id)}):[];patchGroup(g.id,{members:members,member_count:Math.max(1,Number(g.member_count||1)-1)});o.remove();render()}}

  function openManagement(g){document.querySelector('.communityActionOverlay')?.remove();var owner=isOwner(g),state=membership(g),rows='';if(owner){rows+='<button type="button" class="communityManageRow" data-community-edit>Редактировать сообщество <b>›</b></button><div class="communityManageSetting"><span><strong>Кто создаёт события</strong><small>Правило сообщества</small></span><select data-community-event-permission><option value="all">Все участники</option><option value="owner">Только создатель</option></select></div><button type="button" class="communityManageRow" data-community-chat-toggle>'+(g.chat_enabled===true?'Выключить чат':'Включить чат')+' <b>›</b></button><button type="button" class="communityManageRow" data-community-invite>Пригласить людей <b>›</b></button><button type="button" class="communityManageDanger" data-community-delete>Удалить сообщество</button>'}else{rows+='<button type="button" class="communityManageRow" data-community-share>Поделиться <b>›</b></button>';if(state==='member')rows+='<button type="button" class="communityManageDanger" data-community-leave>Покинуть сообщество</button>'}var o=document.createElement('div');o.className='communityActionOverlay';o.innerHTML='<div class="communityActionSheet"><div class="communityActionHead"><div><span class="ey">СООБЩЕСТВО</span><h2>'+esc(g.name)+'</h2></div><button type="button">×</button></div>'+rows+'</div>';document.body.appendChild(o);o.querySelector('.communityActionHead button').onclick=function(){o.remove()};o.onclick=function(e){if(e.target===o)o.remove()};var sel=o.querySelector('[data-community-event-permission]');if(sel){sel.value=g.event_permission||'all';sel.onchange=function(){patchGroup(g.id,{event_permission:sel.value});render()}}var inv=o.querySelector('[data-community-invite]');if(inv)inv.onclick=function(){o.remove();openInvite(g)};var share=o.querySelector('[data-community-share]');if(share)share.onclick=function(){o.remove();openInvite(g)};var chat=o.querySelector('[data-community-chat-toggle]');if(chat)chat.onclick=function(){patchGroup(g.id,{chat_enabled:g.chat_enabled!==true});o.remove();render()};var edit=o.querySelector('[data-community-edit]');if(edit)edit.onclick=function(){o.remove();openEditGroup(g)};var leave=o.querySelector('[data-community-leave]');if(leave)leave.onclick=function(){if(!confirm('Покинуть сообщество «'+g.name+'»?'))return;setMemberState(g,'guest');patchGroup(g.id,{member_count:Math.max(0,Number(g.member_count||1)-1)});o.remove();render()};var del=o.querySelector('[data-community-delete]');if(del)del.onclick=function(){if(!confirm('Удалить сообщество «'+g.name+'»?'))return;var a=groups().filter(function(q){return String(q.id)!==String(g.id)});write(GROUPS_KEY,a);var m=links();Object.keys(m).forEach(function(id){if(String(m[id])===String(g.id))delete m[id]});write(LINKS_KEY,m);o.remove();close()}}
  function openEditGroup(g){document.querySelector('.communityActionOverlay')?.remove();var o=document.createElement('div');o.className='communityActionOverlay';o.innerHTML='<div class="communityActionSheet"><div class="communityActionHead"><div><span class="ey">РЕДАКТИРОВАНИЕ</span><h2>Сообщество</h2></div><button type="button">×</button></div><form class="communityEditForm"><label>Название<input name="name" maxlength="80" required value="'+esc(g.name)+'"></label><label>Описание<textarea name="description" rows="3" maxlength="500">'+esc(g.description||'')+'</textarea></label><fieldset><legend>Доступ</legend><label><input type="radio" name="access" value="open" '+(g.access==='open'?'checked':'')+'> Открытое</label><label><input type="radio" name="access" value="closed" '+(g.access!=='open'?'checked':'')+'> Закрытое</label></fieldset><label class="communityEditCheck"><input type="checkbox" name="chat" '+(g.chat_enabled===true?'checked':'')+'> Чат сообщества</label><button class="communityActionPrimary" type="submit">Сохранить</button></form></div>';document.body.appendChild(o);o.querySelector('.communityActionHead button').onclick=function(){o.remove()};o.onclick=function(e){if(e.target===o)o.remove()};o.querySelector('form').onsubmit=function(e){e.preventDefault();patchGroup(g.id,{name:e.target.elements.name.value.trim(),description:e.target.elements.description.value.trim(),access:e.target.elements.access.value,chat_enabled:!!e.target.elements.chat.checked});o.remove();render()}}

  window.openCommunityDetail=function(id){activeGroupId=id;activeTab='events';lastEvents=null;lastChronicle=null;ensure();if(typeof openView==='function')openView('community-detail');render();loadEvents()};
  ensure();
})();
