(function(){
  var count=0;
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function fmt(v){try{return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'}).format(new Date(v))}catch(e){return''}}
  function badge(sel,n){var b=document.querySelector(sel+' .homeToolBadge');if(!b)return;n=Number(n)||0;b.hidden=n<=0;b.textContent=n>99?'99+':String(n)}
  function badges(){badge('.homeNotifications',count);try{badge('.homeLiked',afishaLiked.size)}catch(e){badge('.homeLiked',0)}try{badge('.homeCompare',afishaCompared.size)}catch(e){badge('.homeCompare',0)}}
  function close(){var o=document.querySelector('.homeToolsOverlay');if(o)o.remove()}
  function sheet(title,body){close();var o=document.createElement('div');o.className='homeToolsOverlay';o.innerHTML='<div class="homeToolsSheet"><div class="homeToolsHead"><h2>'+esc(title)+'</h2><button class="homeToolsClose">×</button></div><div class="homeToolsBody">'+body+'</div></div>';document.body.appendChild(o);o.querySelector('.homeToolsClose').onclick=close;o.onclick=function(e){if(e.target===o)close()};return o}
  async function pending(){if(!account){count=0;badges();return[]}try{var d=await api('list_events');var a=(d.invited_events||[]).filter(function(x){return x.invitation_status==='pending'});count=a.length;badges();return a}catch(e){count=0;badges();return[]}}
  async function notifications(){if(!account){openView('login');return}var o=sheet('Оповещения','<div class="homeToolsEmpty">Загружаю…</div>'),body=o.querySelector('.homeToolsBody'),a=await pending();if(!document.body.contains(o))return;if(!a.length){body.innerHTML='<div class="homeToolsEmpty">Новых уведомлений пока нет.</div>';return}body.innerHTML=a.map(function(x){return'<article class="homeNotification"><small>ПРИГЛАШЕНИЕ</small><h3>'+esc(x.title)+'</h3><p>'+esc(fmt(x.starts_at))+(x.location_name?' · '+esc(x.location_name):'')+'</p><div class="homeNotificationActions"><button class="smallPrimary notifAnswer" data-id="'+esc(x.invitation_id)+'" data-response="accepted">Принять приглашение</button><button class="repeat notifAnswer" data-id="'+esc(x.invitation_id)+'" data-response="declined">Отклонить</button></div></article>'}).join('');body.querySelectorAll('.notifAnswer').forEach(function(b){b.onclick=async function(){b.disabled=true;try{await respondInvitation(b.dataset.id,b.dataset.response);notifications()}catch(e){alert(e.message);b.disabled=false}}})}
  async function liked(){if(!account){openView('login');return}try{if(typeof loadAfisha==='function'&&(!afishaEvents||!afishaEvents.length))await loadAfisha()}catch(e){}var a=[];try{a=afishaEvents.filter(function(x){return afishaLiked.has(x.id)})}catch(e){}var o=sheet('Понравилось',a.length?'':'<div class="homeToolsEmpty">Здесь появятся мероприятия, которым вы поставили ♥.</div>');if(!a.length)return;var body=o.querySelector('.homeToolsBody');body.innerHTML=a.map(function(x){return'<article class="homeLikedItem"><small>'+esc(fmt(x.starts_at))+'</small><h3>'+esc(x.title)+'</h3><p>'+esc(x.venue||'Место уточняется')+'</p><div class="homeLikedActions"><button class="primaryMini likedCollect" data-id="'+esc(x.id)+'">Собрать компанию</button><button class="likedRemove" data-id="'+esc(x.id)+'">Убрать ♥</button></div></article>'}).join('');body.querySelectorAll('.likedCollect').forEach(function(b){b.onclick=function(){close();collectCompany(b.dataset.id)}});body.querySelectorAll('.likedRemove').forEach(function(b){b.onclick=async function(){b.disabled=true;await toggleAfisha('like',b.dataset.id);badges();liked()}})}
  function compare(){if(!account){openView('login');return}var n=0;try{n=afishaCompared.size}catch(e){}if(!n){if(typeof afToast==='function')afToast('Добавьте мероприятия в сравнение');return}if(typeof openAfishaComparison==='function')openAfishaComparison()}
  function bind(){var n=document.querySelector('.homeNotifications'),l=document.querySelector('.homeLiked'),c=document.querySelector('.homeCompare');if(n)n.onclick=notifications;if(l)l.onclick=liked;if(c)c.onclick=compare;badges()}
  bind();setTimeout(function(){bind();pending()},600);setInterval(function(){if(account)pending();else{count=0;badges()}},30000);document.addEventListener('visibilitychange',function(){if(!document.hidden&&account)pending()});
})();
