(function(){
  var section=document.querySelector('[data-view="communities"]');if(!section||section.dataset.peopleV2Mounted==='1')return;section.dataset.peopleV2Mounted='1';
  var root=section.querySelector('#social-hub-root'),search=section.querySelector('#social-hub-search');if(!root||!search)return;
  var CIRCLE_API='https://nmeoakrpafxhpdrplsuo.supabase.co/functions/v1/vmeste-circle-api';
  var PEOPLE_API='https://nmeoakrpafxhpdrplsuo.supabase.co/functions/v1/vmeste-people-api';
  var circleData={accepted:[],incoming:[],outgoing:[]},contextPeople=[],allPeople=[],searchResults=[],loading=false,searchTimer=null,chatTimer=null;
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function session(){try{return JSON.parse(localStorage.getItem('vmeste_session_v1')||'null')}catch(e){return null}}
  function token(){var s=session();return s&&s.access_token||''}
  async function call(url,action,payload,retry){var t=token();if(!t)throw new Error('LOGIN');var r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+t},body:JSON.stringify(Object.assign({action:action},payload||{}))});var d={};try{d=await r.json()}catch(e){d={error:'Некорректный ответ сервера'}}if(r.status===401&&retry!==false&&typeof refreshSession==='function'&&await refreshSession())return call(url,action,payload,false);if(!r.ok)throw new Error(d.error||'Ошибка запроса');return d}
  function peopleActive(){var b=section.querySelector('[data-social-tab="people"]');return !!(section.classList.contains('active')&&b&&b.classList.contains('active'))}
  function inflect(n,one,few,many){var a=Math.abs(n)%100,b=a%10;if(a>10&&a<20)return many;if(b>1&&b<5)return few;if(b===1)return one;return many}
  function relationText(p){var a=[];if(p.common_people_count)a.push(p.common_people_count+' '+inflect(p.common_people_count,'общий человек','общих человека','общих людей'));if(p.common_events_count)a.push(p.common_events_count+' '+inflect(p.common_events_count,'общее событие','общих события','общих событий'));return a.join(' · ')||p.city||'Участник ЛЯ'}
  function avatar(p,attrs){var name=p.display_name||'У';var extra=attrs||'';if(p.avatar_url)return '<button type="button" class="peopleV2Avatar has-photo" style="background-image:url(\''+esc(p.avatar_url)+'\')" '+extra+' aria-label="Открыть профиль"></button>';return '<button type="button" class="peopleV2Avatar" '+extra+' aria-label="Открыть профиль">'+esc(name.trim().slice(0,1).toUpperCase()||'У')+'</button>'}
  function ctxById(id){for(var i=0;i<contextPeople.length;i++)if(contextPeople[i].id===id)return contextPeople[i];return null}
  function requestCard(item){var u=item.user||{},p=ctxById(u.id)||u;return '<article class="peopleV2Card">'+avatar(p,'data-people-profile="'+esc(u.id)+'"')+'<div class="peopleV2Copy"><h3>'+esc(u.display_name||'Участник')+'</h3><p>'+esc(p.common_people_count||p.common_events_count?relationText(p):'Хочет добавить вас в круг')+'</p></div><div class="peopleV2RequestActions"><button type="button" class="peopleV2Accept" data-circle-v2-respond="'+esc(item.connection_id)+'" data-response="accepted">Принять</button><button type="button" class="peopleV2Decline" data-circle-v2-respond="'+esc(item.connection_id)+'" data-response="declined">Отклонить</button></div></article>'}
  function personCard(p){return '<article class="peopleV2Card">'+avatar(p,'data-people-profile="'+esc(p.id)+'"')+'<div class="peopleV2Copy"><h3>'+esc(p.display_name||'Участник')+'</h3><p>'+esc(relationText(p))+'</p></div><button type="button" class="peopleV2Chat" data-people-chat="'+esc(p.id)+'">Написать</button></article>'}
  function searchCard(p){var r=p.relation,action='';if(p.is_self||r&&r.status==='self')action='<button class="peopleV2State" disabled>Вы</button>';else if(!r)action='<button class="peopleV2SearchAction" data-circle-v2-add="'+esc(p.id)+'">Добавить</button>';else if(r.status==='accepted')action='<button class="peopleV2State" disabled>В кругу</button>';else if(r.status==='pending'&&r.direction==='incoming')action='<button class="peopleV2SearchAction" data-circle-v2-respond="'+esc(r.connection_id)+'" data-response="accepted">Принять</button>';else action='<button class="peopleV2State" disabled>Запрос отправлен</button>';return '<article class="peopleV2Card">'+avatar(p,'data-people-search-profile="'+esc(p.id)+'"')+'<div class="peopleV2Copy"><h3>'+esc(p.display_name||'Участник')+'</h3><p>'+esc(p.city||'Участник ЛЯ')+'</p></div>'+action+'</article>'}
  function render(){if(!peopleActive())return;if(loading){root.innerHTML='<div class="peopleV2Loading" data-people-v2-root>Загружаю людей…</div>';return}var q=(search.value||'').trim();if(q.length>=2){root.innerHTML='<div class="peopleV2 peopleV2SearchList" data-people-v2-root>'+(searchResults.length?searchResults.map(searchCard).join(''):'<div class="peopleV2Empty">Никого не нашли. Попробуйте другой запрос.</div>')+'</div>';bindRoot();return}var h='<div class="peopleV2" data-people-v2-root>';
    var incoming=circleData.incoming||[];if(incoming.length){h+='<section class="peopleV2Section"><div class="peopleV2Head"><h2>Входящие запросы</h2><div class="peopleV2HeadMeta"><span class="peopleV2Count">'+incoming.length+'</span>'+(incoming.length>3?'<button type="button" class="peopleV2All" data-people-all="requests">Смотреть все ›</button>':'')+'</div></div><div class="peopleV2List">'+incoming.slice(0,3).map(requestCard).join('')+'</div></section>'}
    var people=contextPeople.slice(0,5);if(contextPeople.length){h+='<section class="peopleV2Section"><div class="peopleV2Head"><h2>Мой круг</h2><div class="peopleV2HeadMeta"><span class="peopleV2Count">'+contextPeople.length+'</span>'+(contextPeople.length>5?'<button type="button" class="peopleV2All" data-people-all="circle">Смотреть все ›</button>':'')+'</div></div><div class="peopleV2List">'+people.map(personCard).join('')+'</div></section>'}var available=allPeople.filter(function(p){var r=p.relation;if(p.is_self||r&&r.status==='self')return false;if(r&&r.status==='accepted')return false;if(r&&r.status==='pending'&&r.direction==='incoming')return false;return true});var directory=available.slice(0,10);if(available.length){h+='<section class="peopleV2Section"><div class="peopleV2Head"><h2>Все в ЛЯ</h2><div class="peopleV2HeadMeta"><span class="peopleV2Count">'+available.length+'</span>'+(available.length>10?'<button type="button" class="peopleV2All" data-people-all="all">Смотреть все ›</button>':'')+'</div></div><div class="peopleV2List">'+directory.map(searchCard).join('')+'</div></section>'}else if(!contextPeople.length&&!incoming.length){h+='<div class="peopleV2Empty">Пока кроме вас никто не зарегистрирован.</div>'}h+='</div>';root.innerHTML=h;bindRoot()}
  async function load(){if(!peopleActive())return;if(!token()){allPeople=[];render();return}loading=true;render();try{var a=await Promise.all([call(CIRCLE_API,'list_circle',{}),call(PEOPLE_API,'people_context',{}),call(CIRCLE_API,'list_people',{})]);circleData=a[0]||circleData;contextPeople=(a[1]&&a[1].people)||[];allPeople=(a[2]&&a[2].people)||[];}catch(e){console.warn('people v2',e)}finally{loading=false;render()}}
  function bindRoot(){root.querySelectorAll('[data-circle-v2-respond]').forEach(function(b){b.onclick=async function(){b.disabled=true;try{await call(CIRCLE_API,'respond_request',{connection_id:b.dataset.circleV2Respond,response:b.dataset.response});await load();document.dispatchEvent(new CustomEvent('vmeste-circle-changed'))}catch(e){alert(e.message);b.disabled=false}}});root.querySelectorAll('[data-circle-v2-add]').forEach(function(b){b.onclick=async function(){b.disabled=true;try{await call(CIRCLE_API,'send_request',{target_user_id:b.dataset.circleV2Add});await doSearch();document.dispatchEvent(new CustomEvent('vmeste-circle-changed'))}catch(e){alert(e.message);b.disabled=false}}});root.querySelectorAll('[data-people-chat]').forEach(function(b){b.onclick=function(){var p=ctxById(b.dataset.peopleChat);if(p)openChat(p)}});root.querySelectorAll('[data-people-profile]').forEach(function(b){b.onclick=function(){var p=ctxById(b.dataset.peopleProfile);if(p)openProfile(p)}});root.querySelectorAll('[data-people-all]').forEach(function(b){b.onclick=function(){openAll(b.dataset.peopleAll)}})}
  async function doSearch(){var q=(search.value||'').trim();if(!peopleActive()||q.length<2){searchResults=[];render();return}try{var d=await call(CIRCLE_API,'search_people',{query:q});searchResults=d.people||[]}catch(e){searchResults=[]}render()}
  function openAll(kind){document.querySelector('.peopleV2SheetOverlay')?.remove();var available=allPeople.filter(function(p){var r=p.relation;if(p.is_self||r&&r.status==='self')return false;if(r&&r.status==='accepted')return false;if(r&&r.status==='pending'&&r.direction==='incoming')return false;return true});var items=kind==='requests'?(circleData.incoming||[]):kind==='all'?available:contextPeople;var title=kind==='requests'?'Входящие запросы':kind==='all'?'Все в ЛЯ':'Мой круг';var body=kind==='requests'?items.map(requestCard).join(''):kind==='all'?items.map(searchCard).join(''):items.map(personCard).join('');var o=document.createElement('div');o.className='peopleV2SheetOverlay';o.innerHTML='<div class="peopleV2Sheet"><div class="peopleV2SheetHead"><h2>'+title+'</h2><button class="peopleV2Close">×</button></div><div class="peopleV2List">'+body+'</div></div>';document.body.appendChild(o);o.querySelector('.peopleV2Close').onclick=function(){o.remove()};o.onclick=function(e){if(e.target===o)o.remove()};o.querySelectorAll('[data-people-chat]').forEach(function(b){b.onclick=function(){var p=ctxById(b.dataset.peopleChat);o.remove();if(p)openChat(p)}});o.querySelectorAll('[data-people-profile]').forEach(function(b){b.onclick=function(){var p=ctxById(b.dataset.peopleProfile);if(p)openProfile(p)}});o.querySelectorAll('[data-circle-v2-respond]').forEach(function(b){b.onclick=async function(){b.disabled=true;try{await call(CIRCLE_API,'respond_request',{connection_id:b.dataset.circleV2Respond,response:b.dataset.response});o.remove();await load()}catch(e){alert(e.message);b.disabled=false}}})}
  function openProfile(p){document.querySelector('.peopleV2ProfileOverlay')?.remove();var o=document.createElement('div');o.className='peopleV2ProfileOverlay';var stats='';if(p.common_people_count)stats+='<span>'+esc(p.common_people_count+' '+inflect(p.common_people_count,'общий человек','общих человека','общих людей'))+'</span>';if(p.common_events_count)stats+='<span>'+esc(p.common_events_count+' '+inflect(p.common_events_count,'общее событие','общих события','общих событий'))+'</span>';o.innerHTML='<div class="peopleV2Profile"><div class="peopleV2ProfileHead"><h2>Профиль</h2><button class="peopleV2Close">×</button></div><div class="peopleV2ProfileHero">'+avatar(p,'')+'<h3>'+esc(p.display_name||'Участник')+'</h3><p>'+esc(p.city||'Участник ЛЯ')+'</p>'+(stats?'<div class="peopleV2ProfileStats">'+stats+'</div>':'')+'</div><button type="button" class="peopleV2ProfileChat">Написать лично</button></div>';document.body.appendChild(o);o.querySelector('.peopleV2Close').onclick=function(){o.remove()};o.onclick=function(e){if(e.target===o)o.remove()};o.querySelector('.peopleV2ProfileChat').onclick=function(){o.remove();openChat(p)}}
  function msgTime(v){try{return new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch(e){return''}}
  async function loadMessages(userId,box){try{var d=await call(PEOPLE_API,'list_messages',{user_id:userId});var m=d.messages||[];box.innerHTML=m.length?m.map(function(x){return '<div class="peopleChatBubble '+(x.mine?'mine':'')+'">'+esc(x.body)+'<time>'+esc(msgTime(x.created_at))+'</time></div>'}).join(''):'<div class="peopleChatEmpty">Начните разговор</div>';box.scrollTop=box.scrollHeight}catch(e){box.innerHTML='<div class="peopleChatEmpty">'+esc(e.message)+'</div>'}}
  function openChat(p){if(chatTimer){clearInterval(chatTimer);chatTimer=null}document.querySelector('.peopleChatOverlay')?.remove();var o=document.createElement('div');o.className='peopleChatOverlay';o.innerHTML='<div class="peopleChatHead"><button class="peopleChatBack">‹</button><div class="peopleChatPerson">'+avatar(p,'data-chat-profile')+'<div><b>'+esc(p.display_name||'Участник')+'</b><small>Личный чат</small></div></div><span></span></div><div class="peopleChatMessages"><div class="peopleChatEmpty">Загружаю…</div></div><form class="peopleChatForm"><textarea maxlength="2000" placeholder="Сообщение"></textarea><button type="submit">↑</button></form>';document.body.appendChild(o);var box=o.querySelector('.peopleChatMessages'),form=o.querySelector('.peopleChatForm'),text=form.querySelector('textarea');var close=function(){if(chatTimer){clearInterval(chatTimer);chatTimer=null}o.remove();load()};o.querySelector('.peopleChatBack').onclick=close;o.querySelector('[data-chat-profile]').onclick=function(){openProfile(p)};form.onsubmit=async function(e){e.preventDefault();var v=text.value.trim();if(!v)return;var send=form.querySelector('button');send.disabled=true;try{await call(PEOPLE_API,'send_message',{user_id:p.id,text:v});text.value='';await loadMessages(p.id,box)}catch(err){alert(err.message)}finally{send.disabled=false}};loadMessages(p.id,box);chatTimer=setInterval(function(){if(document.body.contains(o))loadMessages(p.id,box)},5000)}
  document.addEventListener('click',function(e){var tab=e.target.closest&&e.target.closest('[data-social-tab="people"]');if(tab)setTimeout(load,0);var nav=e.target.closest&&e.target.closest('.nav[data-go="communities"]');if(nav)setTimeout(function(){if(peopleActive())load()},30)},true);
  search.addEventListener('input',function(){if(!peopleActive())return;clearTimeout(searchTimer);searchTimer=setTimeout(doSearch,240)},true);
  var observer=new MutationObserver(function(){if(!peopleActive())return;if(!root.querySelector('[data-people-v2-root]'))setTimeout(function(){if(peopleActive()&&!root.querySelector('[data-people-v2-root]'))render()},0)});observer.observe(root,{childList:true,subtree:false});
  document.addEventListener('vmeste-circle-changed',function(){if(peopleActive())setTimeout(load,40)});
  setTimeout(function(){if(peopleActive())load()},350);
})();
