(function(){
  var returnEventId=null;
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function when(v){try{return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'}).format(new Date(v))}catch(e){return''}}
  function placeKind(p){return({restaurant:'РЕСТОРАН',bar:'БАР',cafe:'КАФЕ',cinema:'КИНОТЕАТР',museum:'МУЗЕЙ',gallery:'ГАЛЕРЕЯ',theatre:'ТЕАТР',club:'КЛУБ',park:'ПАРК',venue:'МЕСТО'})[p.kind]||'МЕСТО'}
  function hero(p){var kind=esc(p.kind||'venue'),cover=p.cover_url?esc(p.cover_url):'';return '<div class="placeHero '+(cover?'hasCover':'placeHeroFallback kind-'+kind)+'"'+(cover?' style="background-image:linear-gradient(180deg,rgba(16,24,43,.08),rgba(16,24,43,.68)),url(&quot;'+cover+'&quot;)"':'')+'><div><span class="ey">'+placeKind(p)+' · '+esc(p.city)+'</span><h1>'+esc(p.name)+'</h1><p class="placeHeroCount"></p></div></div>'}
  function mapUrl(p){return p.map_url||('https://yandex.ru/maps/?text='+encodeURIComponent((p.name||'')+' '+(p.city||'Ростов-на-Дону')))}
  function ensure(){if(document.querySelector('[data-view="place"]'))return;var s=document.createElement('section');s.className='view standalone placeView';s.dataset.view='place';s.innerHTML='<div id="place-detail-root"></div>';var app=document.querySelector('.app');app.insertBefore(s,document.getElementById('bottom-nav'))}
  function close(){var id=returnEventId;returnEventId=null;if(id&&typeof openEventView==='function'){openEventView(id,'calendar');return}openView('home');var n=document.getElementById('bottom-nav');if(n)n.style.display='grid'}
  function createAtPlace(p){if(!account){openView('login');return}returnEventId=null;openView('create');var form=document.getElementById('event-form');if(form)form.hidden=false;var t=document.getElementById('event-title'),pl=document.getElementById('event-place'),u=document.getElementById('event-source');if(t&&!t.value)t.value='Встреча · '+p.name;if(pl)pl.value=p.name;if(u)u.value=mapUrl(p);if(form)setTimeout(function(){form.scrollIntoView({behavior:'smooth',block:'start'})},30)}
  async function open(id,opts){ensure();returnEventId=opts&&opts.returnToEvent?opts.returnToEvent:null;openView('place');var nav=document.getElementById('bottom-nav');if(nav)nav.style.display='none';var root=document.getElementById('place-detail-root');root.innerHTML='<div class="placeViewHead"><button class="placeBack">‹</button></div><p class="muted">Загружаю место…</p>';root.querySelector('.placeBack').onclick=close;try{var d=await afRaw('place_detail',{place_id:id});render(d)}catch(e){root.innerHTML='<div class="placeViewHead"><button class="placeBack">‹</button></div><div class="status error">'+esc(e.message)+'</div>';root.querySelector('.placeBack').onclick=close}}
  window.openPlaceView=open;
  function render(d){var p=d.place,events=d.events||[],root=document.getElementById('place-detail-root');root.innerHTML='<div class="placeViewHead"><button class="placeBack">‹</button><button class="placeViewSave '+(d.saved?'active':'')+'">'+(d.saved?'♥ Сохранено':'♡ Сохранить')+'</button></div>'+hero(p)+'<div class="placeInfoCard"><div class="placeInfoActions"><a class="placeMap" href="'+esc(mapUrl(p))+'" target="_blank" rel="noopener">⌖ Открыть на карте</a><button class="placeMeet">＋ Собрать компанию</button></div></div><div class="placeEventsTitle"><span class="ey">АФИША МЕСТА</span><h2>Что здесь будет</h2></div><div>'+events.map(function(e){return'<article class="placeEvent"><small>'+esc(when(e.starts_at))+'</small><h3>'+esc(e.title)+'</h3><p>'+esc(e.is_free?'Бесплатно':e.price_text||'Цена у организатора')+'</p><div class="placeEventActions"><button class="placeCollect" data-collect="'+esc(e.id)+'">Собрать компанию</button><a class="placeSource" href="'+esc(e.source_url)+'" target="_blank" rel="noopener">Источник ↗</a></div></article>'}).join('')+'</div>';var heroCount=root.querySelector('.placeHeroCount');if(heroCount)heroCount.textContent=events.length?events.length+' событий впереди':'Площадка';root.querySelector('.placeBack').onclick=close;root.querySelector('.placeMeet').onclick=function(){createAtPlace(p)};var save=root.querySelector('.placeViewSave');save.onclick=async function(){if(!account){openView('login');return}save.disabled=true;try{var r=await afRaw('toggle_place_save',{place_id:p.id},true);d.saved=r.saved;save.classList.toggle('active',r.saved);save.textContent=r.saved?'♥ Сохранено':'♡ Сохранить';var a=(window.vmestePlaces||[]).find(function(x){return x.id===p.id});if(a)a.saved=r.saved}catch(e){alert(e.message)}finally{save.disabled=false}};root.querySelectorAll('[data-collect]').forEach(function(b){b.onclick=function(){if(typeof collectCompany==='function')collectCompany(b.dataset.collect)}})}
  ensure();
})();
