(function(){
  var section=document.querySelector('[data-view="communities"]');
  if(!section||section.dataset.socialHubMounted==='1')return;
  section.dataset.socialHubMounted='1';section.classList.add('socialHubView');
  var activeTab='people',communityMode='mine',query='';
  var people=[],friends=[],friendRequests=[],communitiesMine=[],communitiesDiscover=[];
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function peopleIcon(){return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M22 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>'}
  function communityIcon(){return '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3"></circle><path d="M5 19a7 7 0 0 1 14 0"></path><path d="M4.5 10.5A3 3 0 0 0 2 13.5"></path><path d="M19.5 10.5a3 3 0 0 1 2.5 3"></path></svg>'}
  function searchIcon(){return '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-4-4"></path></svg>'}
  function setNav(){var nav=document.querySelector('.nav[data-go="communities"]');if(!nav)return;nav.innerHTML='<svg class="socialNavIcon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3"></circle><path d="M3.5 19a5.5 5.5 0 0 1 11 0"></path><circle cx="17" cy="9" r="2.3"></circle><path d="M15.5 14.6a4.4 4.4 0 0 1 5 4.4"></path></svg><span>Люди</span>'}
  function topAvatar(){var name=(window.account&&window.account.profile&&window.account.profile.display_name)||(window.account&&window.account.user&&window.account.user.email)||'В';return esc(String(name).trim().slice(0,1).toUpperCase()||'В')}
  section.innerHTML='<header class="top socialHubTop"><div><div class="ey">ЛЮДИ</div></div><button class="avatar js-profile" type="button">'+topAvatar()+'</button></header><div class="socialHubTabs"><button type="button" class="active" data-social-tab="people">Люди</button><button type="button" data-social-tab="friends">Друзья</button><button type="button" data-social-tab="communities">Сообщества</button></div><label class="socialHubSearch">'+searchIcon()+'<input id="social-hub-search" type="search" autocomplete="off" placeholder="Найти человека"></label><div class="socialHubRoot" id="social-hub-root"></div>';
  setNav();
  var root=document.getElementById('social-hub-root'),search=document.getElementById('social-hub-search');
  function empty(icon,title,text,action,label){return '<div class="socialEmpty"><div class="socialEmptyIcon">'+icon+'</div><h3>'+esc(title)+'</h3><p>'+esc(text)+'</p>'+(action?'<button type="button" class="socialEmptyAction" data-social-action="'+esc(action)+'">'+esc(label)+'</button>':'')+'</div>'}
  function filtered(items){if(!query)return items;var q=query.toLowerCase();return items.filter(function(x){return String(x.display_name||x.name||x.title||'').toLowerCase().includes(q)})}
  function renderPeople(){var items=filtered(people);if(items.length){root.innerHTML='';return}root.innerHTML=empty(peopleIcon(),query?'Никого не нашли':'Здесь появятся люди',query?'Попробуйте другой запрос.':'Покажем людей, с которыми есть реальный общий контекст: события, места, общие друзья или сообщества.');}
  function renderFriends(){var items=filtered(friends),requests=friendRequests;if(items.length||requests.length){var h='';if(requests.length)h+='<section class="socialHubSection"><div class="socialHubSectionHead"><h2>Запросы</h2><small>'+requests.length+'</small></div><div class="socialHubRequests"></div></section>';if(items.length)h+='<section class="socialHubSection"><div class="socialHubSectionHead"><h2>Друзья</h2><small>'+items.length+'</small></div></section>';root.innerHTML=h;return}root.innerHTML=empty(peopleIcon(),query?'Никого не нашли':'Друзей пока нет',query?'Попробуйте другой запрос.':'Когда вы добавите людей в друзья, они появятся здесь. Отсюда можно будет быстро приглашать их на события.','people','Найти людей');}
  function renderCommunities(){var items=filtered(communityMode==='mine'?communitiesMine:communitiesDiscover);var modes='<div class="socialCommunityModes"><button type="button" data-community-mode="mine" class="'+(communityMode==='mine'?'active':'')+'">Мои</button><button type="button" data-community-mode="discover" class="'+(communityMode==='discover'?'active':'')+'">Найти</button></div>';var body;if(items.length){body='';}else if(query){body=empty(communityIcon(),'Ничего не нашли','Попробуйте изменить запрос.');}else if(communityMode==='mine'){body=empty(communityIcon(),'У вас пока нет сообществ','Здесь будут сообщества, в которых вы состоите, и их ближайшие события.','discover','Найти сообщества');}else{body=empty(communityIcon(),'Сообщества появятся здесь','Покажем реальные сообщества вокруг интересов, мест и событий — без выдуманных карточек.');}root.innerHTML=modes+body;}
  function render(){section.querySelectorAll('[data-social-tab]').forEach(function(b){b.classList.toggle('active',b.dataset.socialTab===activeTab)});search.placeholder=activeTab==='people'?'Найти человека':activeTab==='friends'?'Найти среди друзей':'Найти сообщество';if(activeTab==='people')renderPeople();else if(activeTab==='friends')renderFriends();else renderCommunities()}
  section.querySelector('.js-profile').onclick=function(){if(typeof openView==='function')openView('profile')};
  section.querySelectorAll('[data-social-tab]').forEach(function(b){b.onclick=function(){activeTab=b.dataset.socialTab;query='';search.value='';render()}});
  search.addEventListener('input',function(){query=search.value.trim();render()});
  root.addEventListener('click',function(e){var cm=e.target.closest('[data-community-mode]');if(cm){communityMode=cm.dataset.communityMode;query='';search.value='';render();return}var a=e.target.closest('[data-social-action]');if(!a)return;if(a.dataset.socialAction==='people'){activeTab='people';query='';search.value='';render()}if(a.dataset.socialAction==='discover'){activeTab='communities';communityMode='discover';query='';search.value='';render()}});
  render();
})();
